### PR TITLE
06/23/2020-NAV BAR, about.html, contact.html, created

### PR DESCRIPTION
**Pull request by ctbeam**

### CODE REVIEW

**Review by kenfcheng — COMMENTED** [review]
worst something ever.

**Comment by ctbeam** [comment]
Trying to add Borjan

**Review by kenfcheng — COMMENTED** [review]
random

**Review by kenfcheng — APPROVED** [review]

**Review by ctbeam — COMMENTED** [review]
Great!

**Review by ctbeam — COMMENTED** [review]
These are all awesome!

**Pull request merged**
